#pragma config(CircuitBoardType, typeCktBoardDuemilanove)
#pragma config(Sensor, dgtl8,  SDATA,          sensorDigitalOut)
#pragma config(Sensor, dgtl9,  SCLK,           sensorDigitalOut)
#pragma config(Sensor, dgtl13, LED,            sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*******************************************************************************

Target system-AUrdino Duemilanove Development board s/n-129011
manufacturer: Technophilia
microcontroller: ATmega-328P
clock: 16Mhz
compiler: RobotC
********************************************************************************
SDA-digital8
SCL-digital9
*********************************************************************************/




#include"C:\Users\Malhotra\Desktop\technophilia/ArduinoTwi.h"
#include"C:\Users\Malhotra\Desktop\technophilia/ArduinoLcd.h"

task main ()
{
	unsigned char t=0;
	char str0[14]={'S','h','k','/','T','a','p',' ','D','e','t','e','c','t'};
	char str1[2]={'T','='};
	char str2[7]={'s','h','a','k','i','n','g'};
	char str3[7]={'T','a','p','p','i','n','g'};

	lcd_init();
	lcd_gotoxy(0,0);
	lcd_string(str0,15);
	wait1Msec(500);
	i2c_master_write(0x07,0x00);		// MODE --- Stand By
	i2c_master_write(0x08,0x00);		// SR ---
	i2c_master_write(0x09,0x74);		// PDET ---
	i2c_master_write(0x0A,0x08);		// PD ---
	i2c_master_write(0x07,0x01);		// MODE --- Active
	wait1Msec(200);
  while (true)
  {
  	lcd_clear();
		lcd_gotoxy(0,0);
		lcd_string(str1,2);
		t=i2c_master_read(0x03);      //reading tilt status register
		lcd_showvalue(t);

		if((t & 128)==128)            //detecting shake i.e D7
		{
			lcd_gotoxy(1,0);
			lcd_string(str2,7);
		}
		if((t & 32)==32)             //For tap
		{
			lcd_gotoxy(1,9);
			lcd_string(str3,7);
			SensorValue[led]=true;
		}
		else SensorValue[led]=false;
		wait1Msec(100);
  }
}
